[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"


# ======================================
# INPUT: Membaca data dari Mosquitto
# ======================================

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]

  topics = ["sensor/#"]

  qos = 0

  data_format = "json"

  tag_keys = [
    "device_id",
    "device_name",
    "location",
    "sensor_type",
    "sensor_id"
  ]

  name_override = "sensor"


# ======================================
# OUTPUT: Mengirim data ke InfluxDB v2
# ======================================

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]

  token = "${INFLUXDB_TOKEN}"

  organization = "${INFLUXDB_ORG}"

  bucket = "${INFLUXDB_BUCKET}"